// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjY2NTRlMzVkOTY1MjE5ZmUyZmI2NTBmZjNlZTRhNDlkOWEwMjk3MjMwZjNlZjYxNmM0ZDVjN2RmYjQyZmZmMzU3ZjQ3NWJmMjhmNjliZjBmIn0.eyJhdWQiOiIxIiwianRpIjoiNjY1NGUzNWQ5NjUyMTlmZTJmYjY1MGZmM2VlNGE0OWQ5YTAyOTcyMzBmM2VmNjE2YzRkNWM3ZGZiNDJmZmYzNTdmNDc1YmYyOGY2OWJmMGYiLCJpYXQiOjE1OTc3NTcwODUsIm5iZiI6MTU5Nzc1NzA4NSwiZXhwIjoxNTk3ODQzNDg1LCJzdWIiOiIxMyIsInNjb3BlcyI6W10sInVpZCI6ImE1OGNjYTA3LWVlMjEtNDBlYS1hZjI3LTQ1NzE4MjYwNWE4YiIsIm5hbSI6IlRlc3RlIiwibWFsIjoiYWRtaW5AZGF0d2ViLmNvbSIsImFjYyI6InNvbGlkb3NfdGVtcGxhdGUiLCJlbXAiOiIyYTU0Y2YyNy1iYmI2LTQ5MmYtYTRiYy1hNDVlNDExMzQwNWYiLCJzeXMiOlsiU09MSURPUyIsIkZJU0NBTCJdLCJodHRwczpcL1wvaGFzdXJhLmlvXC9qd3RcL2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzdWFyaW8iXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXN1YXJpbyIsIngtaGFzdXJhLXVzZXItaWQiOiIxMyIsIngtaGFzdXJhLWVtcHJlc2EtdXVpZCI6IjJhNTRjZjI3LWJiYjYtNDkyZi1hNGJjLWE0NWU0MTEzNDA1ZiJ9fQ.rgdHJaKGrrqT4WjPTSWth8oub8GApKCGK_4OP68nRbB1FWfCCr5VkWKt8gN05b-ENWGXyWIhhJPD0zeLPhBiyfyv5RSS9piGeJUTNoWs_ai2CpoWkhUzFKNJmPxzC8WNClbdzU5_nsR9OVQsqbZSF13j2DUJjYZMgnMSoEWUn9mnh7HlAjFBQnlH0wzRTeZrlcAdZKHjo3EoxR9Wmy3_4cuZwUXCSQexmNvpISdRdvTxhhbPfVP4pRnFIkFOfM78gken_mF_8H2RiHqCD2plCQIGEHOjXyuhQPkIHqt4UBc_1XXCYM_i5FsxyszbFUj4Fvz1AMuRlah9I6Re7h3o4TrJJWw7RQuvLv6GV8iMa_2PQsjCf7DE5Xv6xDU832raWXf_H79_2FKbOlAlHWjQnQhPJlMZnOFJ00UBP-7HSOrSgUWAq_-tZdX0eYRxRLUSBHYuwuk87Xurj4_NQ878ItPMsqxlBkmdc34KcE7kVMyyseR_nWStfihiOoo0fGOcSWCAJRsckHv-GH91mkf8bgSrr8oxo6kzKNXNjrgIZb4YAwoW9PgLy7sOCTpzqdwX9DRTSy424emO8o613CxvoeMlFPFXIosS254N1sVnjiKtdRXdjqXxK5ybTsuVg3DqpgLDSYGxO8u8hMddWYygwOiFr-LUqchqkTOWR4NBPrU'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
